name: WebApp CI

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ 'mainline' ]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request's source code
      - name: Checkout the source code
        uses: actions/checkout@v2
      # Setup NodeJS
      - name: SetUp NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # Install node dependencies
      - name: Install Dependencies
        run: npm ci
      - name: Install individual packages dependencies
        run: npm run release:install
      # Make a release build
      - name: Run Release
        run: npm run release